spring:
  application:
    name: facility_tracker-api

  jpa:
    hibernate:
      ddl-auto: validate   # Hibernate checks entities MATCH the schema, never changes it
    show-sql: true
  flyway:
      enabled: true
#      locations: classpath:db/migration

  datasource:
    url: jdbc:mysql://localhost:3306/facility_tracker_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
