@host=http://localhost:8080

### Create customers === success case
POST {{host}}/customers
Content-Type: application/json

{
  "email": "abdul@example.com",
  "fullName": "Ammar Abdulhafiz"
}

### Create customers === blank/invalid email
POST {{host}}/customers
Content-Type: application/json

{
  "email": "",
  "fullName": "Ammar Abdulhafiz"
}

### Create customers === blank/invalid fullName
POST {{host}}/customers
Content-Type: application/json

{
  "email": "a@gmail.com",
  "fullName": " "
}

### Get a specific customer
GET {{host}}/customers/1

### Get all customers
GET {{host}}/customers
