@host=http://localhost:8080

### 1. Create Payment === success case
POST {{host}}/payments
Content-Type: application/json

{
    "facilityId":1,
    "amountPaid":50000
}
###

### 2. Create Payment === invalid facilityId case
POST {{host}}/payments
Content-Type: application/json

{
  "facilityId":-2,
  "amountPaid":500.00

}
###

### 3. Create Payment === invalid amountPaid case
POST {{host}}/payments
Content-Type: application/json

{
  "facilityId":-2,
  "amountPaid": -20

}
###

### 4. get a payment with payment ID
GET {{host}}/payments/1
###

### 5. get all payments == case: All payments irrespective of which facility
GET {{host}}/payments
###


### 6. get all payments == case: All payments of a specific facility
GET {{host}}/payments?facilityId=1
###
